# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: celery-workers
---
# secret
apiVersion: v1
kind: Secret
metadata:
  name: celery-workers-secret
  namespace: celery-workers
type: Opaque
data:
  CELERY_MESSAGE_BROKER_URL: YW1xcDovL2FkbWluOnNlY3JldHBhc3N3b3JkQHJhYmJpdG1xLXNlcnZpY2UucmFiYml0bXEtYnJva2VyOjU2NzI=
  # amqp://admin:secretpassword@rabbitmq-service.rabbitmq-broker:5672
  # amqp://<rabbitmq-user>:<rabbitmq-password>@<service>.<namespace:5672:5672
  CELERY_DATABASE_URL: ZGIrcG9zdGdyZXNxbDovL3Rlc3Q6dGVzdEAxMjNAcG9zdGdyZXMtc2VydmljZS5wb3N0Z3Jlcy1kYXRhYmFzZTo1NDMyL2ZsYXNrLXNlcnZpY2U=
  # db+postgresql://test:test@123@postgres-service.postgres-database:5432/flask-service
  # db+postgresql://<pg-user>:<pg-password>@<service>.<namespace>:<container-port>/<pg-database>
  SECRET_KEY: dGVzdA== # test
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-workers-deployment
  namespace: celery-workers
spec:
  replicas: 2
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: celery-worker
          image: bensmidt/flask-celery-async-microservice
          command:
            - "bash"
            - "-c"
            - "celery -A main.celery worker -l info"
          envFrom:
            - secretRef:
                name: celery-workers-secret
---

