version: '3'
services: 
  locust-load-testing: 
    image: locustio/locust
    ports: 
      - "8089:8089"
    volumes: 
      - ${PWD}:/mnt/locust
    command: -f /mnt/locust/complete_flow_load_test.py