# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: celery-workers
---
# secret
apiVersion: v1
kind: Secret
metadata:
  name: celery-workers-secret
  namespace: celery-workers
type: Opaque
data:
  CELERY_MESSAGE_BROKER_URL: YW1xcDovL2FkbWluOnNlY3JldHBhc3N3b3JkQHJhYmJpdG1xLXNlcnZpY2UucmFiYml0bXEtYnJva2VyOjU2NzI=
  # amqp://admin:secretpassword@rabbitmq-service.rabbitmq-broker:5672
  # amqp://<rabbitmq-user>:<rabbitmq-password>@<service>.<namespace:5672:5672
  # amqp://admin:secretpassword@10.99.71.132:5672
  CELERY_DATABASE_URL: cmVkaXM6Ly86dGVzdEAxMjNAcmVkaXMtc2VydmljZS5yZWRpcy1kYXRhYmFzZTo2Mzc5LzA=
  # redis://:test@123@redis-service.redis-database:6379/0
  # redis://:<redis-database-password>@<service>.<namespace>:<container-port>/
  SECRET_KEY: dGVzdA== # test
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-workers-deployment
  namespace: celery-workers
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: celery-worker
          image: bensmidt/flask-celery-async-microservice
          command:
            - "bash"
            - "-c"
            - "celery -A main.celery worker -l info"
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: 'all'
          envFrom:
            - secretRef:
                name: celery-workers-secret
---

