version: '3'
services: 

  redis-backend: 
    image: redis:latest
    ports: 
      - 6379:6379

  rabbitmq-message-broker: 
    image: rabbitmq:latest
    ports: 
      - 5672:5672
      - 15672:15672
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest