FROM python:3.10.12

WORKDIR /usr/app

COPY ./requirements.txt ./requirements.txt

RUN pip3 install --upgrade pip && \
    pip3 install --no-cache-dir -r requirements.txt

CMD celery -A tasks worker --loglevel=info